theme = "monokai"

[editor]
# Show currently open buffers, only when more than one exists. 
bufferline = "multiple" 
# Highlight all lines with a cursor 
cursorline = true 
# Use relative line numbers 
line-number = "relative" 
# Show a ruler at column 120 
rulers = [120] 
# Force the theme to show colors 
true-color = true

[editor.lsp] 
# Disable automatically popups of signature parameter help 
#auto-signature-help = false
# Show LSP messages in the status line 
display-messages = true
