[tools]
go = "1.26.4"
node = "22"
"npm:prettier" = "latest"
pnpm = "latest"
python = "3.12.7"
uv = "latest"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
python.github_attestations = false
